# SmallRye OpenAPI configuration
quarkus.smallrye-openapi.info-title=Minha API Quarkus
quarkus.smallrye-openapi.info-version=1.0.0
quarkus.smallrye-openapi.info-description=Exemplo de API documentada com OpenAPI

# Datasource configuration for H2 in-memory database
quarkus.datasource.db-kind=h2
#quarkus.datasource.jdbc.url=jdbc:h2:file:D:/Projects/h2-2025-09-22/lifeguard;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
quarkus.datasource.jdbc.url=jdbc:h2:tcp://localhost/~/lifeguard
quarkus.datasource.username=sa
quarkus.datasource.password=
quarkus.hibernate-orm.dialect=org.hibernate.dialect.H2Dialect
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.database.generation=update

